services:
  traefik:
    image: "traefik:v3.6.5"
    container_name: "traefik"
    restart: unless-stopped
    environment:
      - CF_DNS_API_TOKEN=${CF_API_TOKEN}
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    ports:
      - "80:80"
      - "443:443"
      - "8088:8080"
    volumes:
      - "traefik.enabled=true"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/traefik-config.yml:/etc/traefik/traefik.yml:ro"
      - "./traefik/dynamic:/dynamic:ro"
      - "./traefik/logs:/logs"
      - "./traefik/acme.json:/acme.json"


  whoami:
    image: "traefik/whoami"
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=web"

  # cloudflare-ddns:
  #   image: favonia/cloudflare-ddns:latest
  #   container_name: cloudflare-ddns
  #   restart: unless-stopped
  #   network_mode: host
  #   cap_drop:
  #     - ALL
  #   read_only: true
  #   security_opt:
  #     - no-new-privileges:true
  #   environment:
  #     - CF_API_TOKEN=${CF_API_TOKEN}
  #     - DOMAINS=jf.hrolgar.com,auth.hrolgar.com
  #     - PROXIED=false
  #     - IP6_PROVIDER=none
  #     - UPDATE_CRON=*/5 * * * *
  #     - DELETE_ON_STOP=false
  #     - CACHE_EXPIRATION=6h
  postgresql:
    image: postgres:16-alpine
    container_name: authentik-postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${AUTHENTIK_PG_PASS}
      - POSTGRES_USER=authentik
      - POSTGRES_DB=authentik
    networks:
      - authentik-internal

  redis:
    image: redis:alpine
    container_name: authentik-redis
    restart: unless-stopped
    command: --save 60 1 --loglevel warning
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    volumes:
      - ./data/redis:/data
    networks:
      - authentik-internal

  server:
    image: ghcr.io/goauthentik/server:2024.10.4
    container_name: authentik-server
    restart: unless-stopped
    command: server
    environment:
      - AUTHENTIK_REDIS__HOST=redis
      - AUTHENTIK_POSTGRESQL__HOST=postgresql
      - AUTHENTIK_POSTGRESQL__USER=authentik
      - AUTHENTIK_POSTGRESQL__NAME=authentik
      - AUTHENTIK_POSTGRESQL__PASSWORD=${AUTHENTIK_PG_PASS}
      - AUTHENTIK_SECRET_KEY=${AUTHENTIK_SECRET_KEY}
      - AUTHENTIK_ERROR_REPORTING__ENABLED=false
    volumes:
      - ./media:/media
      - ./templates:/templates
    depends_on:
      postgresql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - authentik-internal
      - proxy
    labels:
      - "traefik.enable=true"
      # Main Authentik UI
      - "traefik.http.routers.authentik.rule=Host(`auth.hrolgar.com`)"
      - "traefik.http.routers.authentik.entrypoints=https"
      - "traefik.http.routers.authentik.tls=true"
      - "traefik.http.routers.authentik.tls.certresolver=cloudflare"
      - "traefik.http.routers.authentik.service=authentik-svc"
      - "traefik.http.services.authentik-svc.loadbalancer.server.port=9000"
      # Outpost routes for forward auth
      - "traefik.http.routers.authentik-outpost.rule=HostRegexp(`{subdomain:[a-z0-9-]+}.hrolgar.com`) && PathPrefix(`/outpost.goauthentik.io/`)"
      - "traefik.http.routers.authentik-outpost.entrypoints=https"
      - "traefik.http.routers.authentik-outpost.tls=true"
      - "traefik.http.routers.authentik-outpost.service=authentik-svc"

  worker:
    image: ghcr.io/goauthentik/server:2024.10.4
    container_name: authentik-worker
    restart: unless-stopped
    command: worker
    environment:
      - AUTHENTIK_REDIS__HOST=redis
      - AUTHENTIK_POSTGRESQL__HOST=postgresql
      - AUTHENTIK_POSTGRESQL__USER=authentik
      - AUTHENTIK_POSTGRESQL__NAME=authentik
      - AUTHENTIK_POSTGRESQL__PASSWORD=${AUTHENTIK_PG_PASS}
      - AUTHENTIK_SECRET_KEY=${AUTHENTIK_SECRET_KEY}
      - AUTHENTIK_ERROR_REPORTING__ENABLED=false
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./media:/media
      - ./templates:/templates
      - ./certs:/certs
    depends_on:
      postgresql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - authentik-internal

networks:
  authentik-internal:
    driver: bridge
  proxy:
    external: true